# message 241

char[4] sol_stat
char[4] pos_type

float64 northing
float64 easting
float64 height

float32 northing_std
float32 easting_std
float32 height_std

char[4] vel_stat
char[4] vel_type

float64 velx
float64 vely
float64 velz

float32 velx_std
float32 vely_std
float32 velz_std

char[4] stn_id

float32 vel_latency

float32 diff_age
float32 sol_age

uint8 svs
uint8 sol_svs
uint8 l1_svs
uint8 mult_svs
uint8 reserved
uint8 extsolstat
uint8 gal_sig_mask
uint8 sig_mask
