# message 1465
novatel_msgs/CommonHeader header

float64 gpssec=0

uint8[4] status
uint8[4] pos_type

float64 latitude
float64 longitude
float64 altitude

float32 undulation

float64 velx
float64 vely
float64 velz

float64 roll
float64 pitch
float64 azimuth

float32 latitude_std
float32 longitude_std
float32 altitude_std

float32 velx_std
float32 vely_std
float32 velz_std

float32 roll_std
float32 pitch_std
float32 azimuth_std

uint8[4] extsolstat

uint16 timesince_posupdate
